### ISSUE TITLE
Rework custom size configuration UI

### ISSUE THREAD

**Issue by jakobharder** [anno-mods/AnnoMapEditor#33]
Remove duplicate information.
Easy mode should be a lot simpler, less cluttered.

**Comment by Shad0wlife** [comment]
Idea: remove the slider(s) and make the playable area configuration draggable in the visual section?
Might be complicated but potentially makes it more user friendly?
Als maybe turn it into a "mode" so that during playable area resizing, islands can't be dragged/dont capture clicks?

We should still show the Position and size info somewhere though.

**Comment by Shad0wlife** [comment]
Should be fixed by #51 . That PR changes it, so the overall size is a single slider, and the playable area can be dragged and resized on map (when enabled).

**Comment by Shad0wlife** [comment]
Closed by #51.
If not satisfactory, reopen please ;)
