### ISSUE TITLE
Changing margin creates off-centered PlayableArea

### ISSUE THREAD

**Issue by jakobharder** [anno-mods/AnnoMapEditor#35]
Only moving the margin slide should never lead to a non-centered PlayableArea.

**Comment by Shad0wlife** [comment]
There is (or at leadt used to be) a reason for that: To reduce the number of sliders, the margin slider sets the Total margin used (on both sides of the playavle area). If that number is uneven, we would have an off-tile playable area, which isn't allowed. Thus, we have to add 1 tile more margin on one of the sides.

(Maybe the slider doesn't set the total margin but the average margin? In which case we have values which are half of a tile (eg. 44 coords = 5xTile +0,5xTile). The effect is the same - we need a default offset.)

Why was this introduced? Some of the vanilla maps are offcenter like this, so we need to allow the "uneven" margin confugurations and handle them correctly - and (somewhat) gracefully.

**Comment by Shad0wlife** [comment]
Should be fixed by #51 , as the Margin is not managed by a slider anymore then, but by dragging the playable area on the map view.

**Comment by Shad0wlife** [comment]
Off center playable areas are a thing, also in vanilla maps. But since the playable area resizing is now a visual control directly related to its position on the map, and not a slider anymore, I think this does not pose an issue anymore, since resizing the playable area to be off center now is a purposeful manual operation.
